### ISSUE TITLE
High battery and Data usage on Android

### ISSUE THREAD

**Issue by bhurinuthw** [codeforpublic/SQUID#39]
App uses very high battery due to location tracking.  
Data usage is also very high.

**Comment by bact** [comment]
![136986210_193382412485842_811819743688194697_n](https://user-images.githubusercontent.com/128572/103895683-5f545680-5123-11eb-9624-85f3c53173a3.png)

From one case on Android, the app consumes 10 GB over 7 days of use.

**Comment by neetrath** [comment]
There could be problems on some device model because my Android device just consumes 6.05 MB since 1st Jan


![Screenshot_20210107-202746_Settings](https://user-images.githubusercontent.com/2845862/103898586-bb20de80-5127-11eb-9ee3-61378224894e.jpg)

Btw, it needs to be fixed.

**Comment by bact** [comment]
Another case here 
https://www.facebook.com/McDuck/posts/10221519050437110

**Comment by nanusorn** [comment]
![137225542_10221519000955873_1895296419154817972_n](https://user-images.githubusercontent.com/277424/104036933-a109fd80-5206-11eb-9f80-d567c523d9a1.jpg)
![137256933_10221519000835870_195652281510297476_n](https://user-images.githubusercontent.com/277424/104036942-a2d3c100-5206-11eb-8c23-0df01e63d313.jpg)

**Comment by boysbee** [comment]
Me too.
Device Huawei Mate 20 Pro
Android Version 10
enable loction all day.

![Screenshot_20210108_234835_com huawei systemmanager](https://user-images.githubusercontent.com/369291/104042417-124caf00-520d-11eb-9884-ab391c497e3e.jpg)

**Comment by PH9** [comment]
Seem to have a problem with the Android devices.

**Comment by kajornsakp** [comment]
For network consumption issue, I've roughly (very roughly) profiled the app on both iOS and Android via Charles as well. These are some information that might be useful.

Hypothesis
Based on reports (This issue and on social network) Android devices are consuming data more than iOS devices. Therefore, there might be some different behavior on each platform. In this case, data consumption might come from network request during device handshaking.

Devices
- iPhone 12 Pro Max, iOS 14.3, non-jailbroken
- Samsung Galaxy Z Flip 2, Android 10, non-rooted

Controlled conditions
- Morchana app version 2.0.1
- Same set of permissions allowed
    - GPS: When in use only since most of the reports showed that mobile network used on Foreground ✅ 
    - Bluetooth ✅ 
    - Motion & Activity ✅ 
    - Notification ✅ 
- Putting 2 devices next to each other while opening Morchana app. No user event. No force refresh QR code. 


Recording period: 2 minutes via Charles proxy to get size of network request

Result
iOS: 13 requests, 26.76 KB each, In total = 347.88 KB
Android: 23 requests, 26.68 KB each, In total = 613.64 KB

Android device (my device) is sending more network requests than iOS (70% more). 

With this rate of network request. Let's say user use this app 6 hours in public. It'll consumed at least 93.7 MB of data per day which is a lot of data 😅  (assume that numbers of scanned devices are not affecting uploading rate)

As I roughly check the code (which might not be the same one on store). Request should be sent once every 30 mins? instead of this rate. Also, code on `contract-tracer` module looks fine for me. So it shouldn't related to ble scanning logic.

Summary 
1. Response size from api should be smaller with this high rate of scanned nearby device uploading
2. Something wrong with network request rate 😅

![Screen Shot 2021-01-10 at 01 56 57](https://user-images.githubusercontent.com/10228783/104106272-282ea280-52e7-11eb-9897-85b7e186282e.png)
![Screen Shot 2021-01-10 at 01 56 49](https://user-images.githubusercontent.com/10228783/104106275-2bc22980-52e7-11eb-8771-9e81ce1fbe4f.png)

Hope this might be helpful for further investigation

**Comment by PaperMonster** [comment]
@kajornsakp I tried my Android 10 device (in foreground, app version 2.0.1) with Charles and saw only few requests in sequence view. Is there any extra config needed to see a lot of requests like you did?
![Screen Shot 2564-01-10 at 14 14 16](https://user-images.githubusercontent.com/10735822/104116857-e9343780-534e-11eb-8f35-e31e500f1ff5.png)

**Comment by kajornsakp** [comment]
@PaperMonster Hmm, that's weird 🤔 . I just opened 2 devices and let it scan for each other. No need to set extra config in Charles

**Comment by PaperMonster** [comment]
@kajornsakp I forgot to open 2 devices next to each other. Once I do, I got more requests from both devices, but not as often as you did. iOS took 1-2 minutes per request while Android hardly sent requests after launch. Gotta play with them more later.

**Comment by PH9** [comment]
![FB_IMG_1610363389676](https://user-images.githubusercontent.com/6365973/104173450-5d96d580-5438-11eb-9ab1-546b623bbf27.jpg)

**Comment by bact** [comment]
High data usage links to at least two problems:
1) bills
2) battery

Free data usage may solved (1) - for likely a limited period of time, as this can't be forever.
